### ISSUE TITLE
Pin C* to 2.1

### ISSUE THREAD

**Issue by spladug** [reddit/baseplate-cookiecutter#5]
We're not going to be bleeding edge here yet, so make dev closer to prod.

**Comment by pacejackson** [comment]
This is what I have currently:

```
  package { 'cassandra':
    ensure  => "2.1.15",
    require => Class['cassandra::java'],
  }
```

**Comment by spladug** [comment]
We decided to go for 2.2. Done in e7b26aecc4400222b35830606ad3881b5a18b699.
