### ISSUE TITLE
Cassandra template needs session obj

### ISSUE THREAD

**Issue by pacejackson** [reddit/baseplate-cookiecutter#7]
If you add the Cassandra integration to your project, the following lines are added to your __init__.py.

```python
cluster = cluster_from_config(app_config, prefix="cassandra.")
baseplate.add_to_context("cassandra", CassandraContextFactory(cluster))
```

These don't actually work though because CassandraContextFactory needs a Session object, not a Cluster.  What we likely need is something a little more like this...

```
cluster = cluster_from_config(app_config, prefix="cassandra.")
session = cluster.connect({{project_name}})
baseplate.add_to_context("cassandra", CassandraContextFactory(session))
```

**Comment by spladug** [comment]
Fixed in 2dc785153fc273636db0439878ec3b9a98599c9a
